# Generated by Django 3.0.9 on 2020-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='34276717886b4141a81f9d9412a1588a', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_request',
            field=models.CharField(default=1, max_length=260),
            preserve_default=False,
        ),
    ]
