# Generated by Django 3.0.9 on 2020-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200803_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='d9293759bb3149b69335485a7f1a915a', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_request',
            field=models.CharField(default='', max_length=260),
        ),
    ]
