# Generated by Django 3.0.9 on 2020-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200803_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='f5bf7e06a85c499f973b414334599f04', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_request',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
