# Generated by Django 3.0.9 on 2020-08-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200803_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='a18ce221cf8740d3abc5afdfe42fb9b7', max_length=32),
        ),
    ]
