# Generated by Django 3.0.9 on 2020-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200803_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='0962fe29afd64536b68e6ba6b476c0fd', max_length=32),
        ),
    ]
