# Generated by Django 3.0.9 on 2020-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200805_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='6c3a088932fc4cdcadc87054ffdc21b5', max_length=32),
        ),
    ]
