# Generated by Django 3.0.9 on 2020-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200805_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='f72a4e427ee74b55a898d5f109990c86', max_length=32),
        ),
    ]
