# Generated by Django 3.0.9 on 2020-08-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200810_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_sats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='be20c9f26308438e9430313c5eeef880', max_length=32),
        ),
    ]
