version: '3'
services:
  chaos:
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
      - "8080:8080"
    volumes:
        - /home/skorn/Documents/lightning/lnshop/mysite:/usr/src/app/db